export const CREATE_MENTOR_ERROR = 'CREATE_MENTOR_ERROR';
export const CREATE_MENTOR_SUCCESS = 'CREATE_MENTOR_SUCCESS';

export const DELETE_MENTOR_ERROR = 'DELETE_MENTOR_ERROR';
export const DELETE_MENTOR_SUCCESS = 'DELETE_MENTOR_SUCCESS';

export const UNDELETE_MENTOR_ERROR = 'UNDELETE_MENTOR_ERROR';

export const UPDATE_MENTOR_ERROR = 'UPDATE_MENTOR_ERROR';
export const UPDATE_MENTOR_SUCCESS = 'UPDATE_MENTOR_SUCCESS';

export const SHOW_DETAIL_MENTOR_SUCCESS = 'SHOW_DETAIL_MENTOR_SUCCESS';
export const SHOW_DETAIL_MENTOR_ERROR = 'SHOW_DETAIL_MENTOR_ERROR';


export const FILTER_MENTORS = 'FILTER_MENTORS';
export const LOAD_MENTORS_SUCCESS = 'LOAD_MENTORS_SUCCESS';
export const UNLOAD_MENTORS_SUCCESS = 'UNLOAD_MENTORS_SUCCESS';
